name: deploy
on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2
          run_install: true

      - name: Create release
        run: pnpm run release
